// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ISanctionsOracle} from "./interfaces/ISanctionsOracle.sol";
import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title  SanctionsOracle
 * @author Mantle RWA Team
 * @notice On-chain AML blacklist registry that gates MantleYieldVault operations.
 *
 * @dev    Architecture position
 *         ─────────────────────
 *         • Upstream  : MantleYieldVault calls `isSanctioned()` inside deposit / redeem / transfer hooks.
 *         • Writer    : Off-chain Sanctions Service holds `COMPLIANCE_ROLE` and pushes incremental updates.
 *         • Data feed : Chainalysis / Elliptic / OFAC (aggregated off-chain, delta-compressed before pushing).
 *
 *         Design principles
 *         ─────────────────
 *         1. **Smart batching**  — Only SSTORE when status actually flips; redundant entries are skipped.
 *         2. **Gas-bounded**     — `MAX_BATCH_SIZE` hard-caps loop iterations to prevent griefing.
 *         3. **O(1) reads**      — Single SLOAD per `isSanctioned` call (< 3 000 gas in Vault hooks).
 *         4. **Audit trail**     — Monotonic `batchNonce` + per-address events for off-chain indexing.
 *         5. **Fail-safe**       — If the Compliance Service errors, no state is cleared; existing bans stay.
 *         6. **Minimal surface** — `COMPLIANCE_ROLE` can only toggle booleans; it cannot touch Vault funds.
 *
 *         Error recovery
 *         ──────────────
 *         If a legitimate user is mistakenly sanctioned:
 *           a) User files an appeal off-chain.
 *           b) Admin (multisig) instructs the Compliance Bot → `updateSanctionStatus(addr, false)`.
 *           c) Or Admin grants itself `COMPLIANCE_ROLE` for an emergency unsanction.
 */
contract SanctionsOracle is ISanctionsOracle, AccessControl {
    // ─────────────────────────────────────────────────────────────
    //                          CONSTANTS
    // ─────────────────────────────────────────────────────────────

    /// @notice Role granted to the off-chain Compliance Bot.
    bytes32 public constant COMPLIANCE_ROLE = keccak256("COMPLIANCE_ROLE");

    /// @notice Hard ceiling on addresses per batch call to bound gas usage.
    /// @dev    200 addresses ≈ 1.4 M gas worst-case (cold SSTORE); fits comfortably in a single block.
    uint256 public constant MAX_BATCH_SIZE = 200;

    // ─────────────────────────────────────────────────────────────
    //                            STATE
    // ─────────────────────────────────────────────────────────────

    /// @notice Core mapping: `true` ⇒ address is currently sanctioned / blacklisted.
    /// @dev    Exposed as a public getter satisfying `ISanctionsOracle.isSanctioned`.
    mapping(address account => bool sanctioned) public isSanctioned;

    /// @notice Running count of distinct sanctioned addresses.
    uint256 public totalSanctionedCount;

    /// @notice Block timestamp of the most recent state-mutating update.
    /// @dev    Off-chain monitoring uses this to detect Compliance Bot liveness issues.
    uint256 public lastUpdateTimestamp;

    /// @notice Monotonically increasing counter; incremented on every batch call.
    /// @dev    Allows off-chain systems to correlate on-chain events with their job IDs.
    uint256 public batchNonce;

    // ─────────────────────────────────────────────────────────────
    //                         CONSTRUCTOR
    // ─────────────────────────────────────────────────────────────

    /**
     * @param admin_         Address receiving `DEFAULT_ADMIN_ROLE` (typically a multisig / timelock).
     * @param complianceBot_ Address receiving `COMPLIANCE_ROLE` (the off-chain Sanctions Service hot-wallet).
     */
    constructor(address admin_, address complianceBot_) {
        if (admin_ == address(0)) revert Oracle__ZeroAddress();
        if (complianceBot_ == address(0)) revert Oracle__ZeroAddress();

        _grantRole(DEFAULT_ADMIN_ROLE, admin_);
        _grantRole(COMPLIANCE_ROLE, complianceBot_);

        lastUpdateTimestamp = block.timestamp;
    }

    // ─────────────────────────────────────────────────────────────
    //                          ERC-165
    // ─────────────────────────────────────────────────────────────

    /// @dev Declare support for ISanctionsOracle so Vault can verify the oracle at setup time.
    function supportsInterface(bytes4 interfaceId) public view override returns (bool) {
        return interfaceId == type(ISanctionsOracle).interfaceId || super.supportsInterface(interfaceId);
    }

    // NOTE: `isSanctioned(address)` is auto-generated by the public mapping and satisfies the interface.

    // ─────────────────────────────────────────────────────────────
    //                       WRITE FUNCTIONS
    // ─────────────────────────────────────────────────────────────

    /// @inheritdoc ISanctionsOracle
    function updateSanctionStatus(address account, bool sanctioned) external onlyRole(COMPLIANCE_ROLE) {
        if (account == address(0)) revert Oracle__ZeroAddress();

        uint256 changed;

        if (isSanctioned[account] != sanctioned) {
            isSanctioned[account] = sanctioned;

            if (sanctioned) {
                unchecked {
                    ++totalSanctionedCount;
                }
            } else {
                // Safe: count ≥ 1 because `isSanctioned[account]` was `true`.
                unchecked {
                    --totalSanctionedCount;
                }
            }

            lastUpdateTimestamp = block.timestamp;
            changed = 1;

            emit SanctionStatusUpdated(account, sanctioned);
        }

        // Batch event with processed=1 for consistent off-chain indexing.
        uint256 nonce;
        unchecked {
            nonce = batchNonce++;
        }
        emit BatchSanctionUpdated(nonce, 1, changed, sanctioned);
    }

    /// @inheritdoc ISanctionsOracle
    function updateSanctionStatusBatch(address[] calldata accounts, bool sanctioned)
        external
        onlyRole(COMPLIANCE_ROLE)
    {
        uint256 len = accounts.length;
        if (len == 0) revert Oracle__EmptyArray();
        if (len > MAX_BATCH_SIZE) revert Oracle__BatchTooLarge(len, MAX_BATCH_SIZE);

        // Cache in memory to avoid repeated SLOAD / SSTORE inside the loop.
        uint256 cachedCount = totalSanctionedCount;
        uint256 effectiveChanges;

        for (uint256 i; i < len;) {
            address account = accounts[i];
            if (account == address(0)) revert Oracle__ZeroAddress();

            if (isSanctioned[account] != sanctioned) {
                isSanctioned[account] = sanctioned;

                if (sanctioned) {
                    unchecked {
                        ++cachedCount;
                    }
                } else {
                    unchecked {
                        --cachedCount;
                    }
                }

                emit SanctionStatusUpdated(account, sanctioned);

                unchecked {
                    ++effectiveChanges;
                }
            }

            unchecked {
                ++i;
            }
        }

        // Single SSTORE for count (only if something changed).
        if (effectiveChanges > 0) {
            totalSanctionedCount = cachedCount;
            lastUpdateTimestamp = block.timestamp;
        }

        // Always emit the batch event so off-chain can track every invocation.
        uint256 nonce;
        unchecked {
            nonce = batchNonce++;
        }
        emit BatchSanctionUpdated(nonce, len, effectiveChanges, sanctioned);
    }
}
